### ISSUE TITLE
npm missing from our images causing all the "New CDT" builds to fail

### ISSUE THREAD

**Issue by dschaefer** [eclipse-cdt/cdt-infra#8]
Any tips on how I can add it. Might be good to have something in the Wiki for future reference.

Thanks!

**Comment by Kummallinen** [comment]
Think the issue is acutally most of the New CDT jobs haven't been migrated ot use one of our pod images. https://ci.eclipse.org/cdt/view/New%20CDT/job/cdt-vscode-pipelinetest/ works, so think all the required stuff is in there.

Should just be a case of migrating the jobs to pipelines based on that one.

**Comment by dschaefer** [comment]
Ah, cool. I'll take a look.

**Comment by Kummallinen** [comment]
The main image has Node 8.x in it (https://github.com/eclipse-cdt/cdt-infra/blob/2863728b0883a86202d5aee53fd9b28ded7cc569/docker/cdt-infra-eclipse-full/ubuntu-16.04/Dockerfile#L30)

**Comment by dschaefer** [comment]
Cool. We'll need to upgrade that to 10.x since that's what VS Code has in it. Unless there's something else we need node 8 for?

**Comment by Kummallinen** [comment]
Some of the Eclipse plugins need node.js I think, not sure if there is a specific version requirement. @jonahgraham , any idea?

**Comment by dschaefer** [comment]
Anyway, got a couple of the builds going. Have a couple of more issues to figure out but not really blocked. Closing this and will raise new ones if I get stuck. Thanks!
